#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(grep -E "^Host " ~/.ssh/config | grep -v "#" | sed "s/^Host //" | tr " " "\n" | grep -v "^$" | grep -v "[*?]" | sort -u | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux new-window -n "🔌$selected" "ssh $selected"
