import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

window.opacity = 0.85 
live_config_reload = true


[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.padding]
x = 16
y = 16

[shell]
program = "/usr/bin/zsh"
